<?php
$translations = [
    /* ----------------------------------- nav ---------------------------------- */
    "home" => "Inicio",
    "skills" => "Habilidades",
    "timeline" => "Cronología",
    "projects" => "Proyectos",
    /* --------------------------------- Landing -------------------------------- */
    "job" => "Master en Ciencias Cognitivas | Investigadora UX | Factores Humanos",
    "about" => "Soy estudiante de último año de un Máster en Ciencias Cognitivas, especializado en Interacción Humano-Máquina, Investigación UX, Factores Humanos y Ciencias del Comportamiento. Mi trabajo se centra en comprender cómo las personas interactúan con la tecnología y cómo los principios de las ciencias cognitivas pueden aplicarse al diseño de sistemas intuitivos, fiables y fundamentados en evidencia científica.",
    "about2" => "Actualmente, mi investigación se enfoca en el sesgo de automatización (automation bias), la toma de decisiones y el diseño de sistemas, analizando cómo el diseño de interfaces y la automatización influyen en el juicio humano. Mediante métodos de psicología experimental, estudio los mecanismos cognitivos que intervienen en la interacción entre humanos e inteligencia artificial con el objetivo de diseñar sistemas de apoyo a la decisión más seguros y eficaces.",
    "project-button" => "Descubre mi proyecto de investigación",
    "contact-button" => "Contáctame",
    /* --------------------------------- Skills --------------------------------- */
    "skills-h1" => "Habilidades",
    "skills-h2-dev" => "Desarrollo",
    "skills-h2-design" => "Diseño",
    "skills-h2-gestion" => "Gestión",
    "skills-h2-other" => "Otros",
    /* -------------------------------- Timeline -------------------------------- */
    "timeline-h1" => "Cronología",
    "bac-h3" => "Bachillerato: Especialidades Matemáticas y Humanidades, Filosofía y Literatura",
    "bac-location" => "Liceo Francés de San Salvador, El Salvador",
    "licence-h3" => "Licenciatura en Informática",
    "licence-location" => "Universidad de Estrasburgo, Francia",
    "adem-h3" => "Encargada de misión local - ADEM",
    "adem-location" => "Amicale des Étudiant·e·s en Mathématiques (ADEM), Estrasburgo, Francia",
    "touch-tech-h3" => "Community Manager - Touch Tech",
    "touch-tech-location" => "Touch Tech, El Salvador - A distancia",
    "aius-h3" => "Responsable de Comunicación - AIUS",
    "aius-location" => "Association des Informaticien·ne·s de l'Université de Strasbourg, Francia",
    "lp-h3" => "Licenciatura Professional - Estrategias de la comunicación y de la información digital",
    "lp-location" => "IUT Robert Schuman, Illkirch, Francia",
    "studio-h3" => "Pasantía en Comunicación - Studio Lab'Ut",
    "studio-location" => "Studio Lab'Ut, Estrasburgo, Francia",
    "master-h3" => "Máster en Ciencias Cognitivas para la Empresa",
    "master-location" => "Universidad de Lille, Francia",
    "master-location-lab" => "Sciences Cognitives et Sciences Affectives SCALab, Universidad de Lille, Francia",
    "master-thesis-internship" => "Pasantía de investigación - Thesis de Master: Sesgo de automatización y toma de decisiones",
    /* -------------------------------- Projects Portfolio -------------------------------- */
    "project-h1" => "Proyectos",
    "project-page-desc-h2" => "Descripción del proyecto",
    "portfolio-project-desc" => "Este proyecto se centra en la creación de un sitio web funcional y accesible. El diseño minimalista, creado con Lunacy, fue desarrollado utilizando tecnologías modernas como HTML, CSS, PHP y JavaScript. El objetivo principal era garantizar la accesibilidad a un público amplio, integrando un módulo de traducción en PHP para permitir el uso multilingüe. El proceso de gestión de versiones se optimizó a través de GitHub. Este proyecto demuestra mi capacidad para diseñar soluciones web eficaces, fáciles de usar y optimizadas para un público diverso. Puedes consultar el proyecto en mi ",
    "used-tech" => "Tecnologías utilizadas" ,
    "galery" => "Galería",
    /* --------------------------- Project Touch Tech --------------------------- */
    "touchtech-project-desc" => "Touch Tech es una empresa B2B que ofrece servicios en la nube y externalización. Comencé a trabajar con ellos en 2021, donde fui responsable de la comunicación a través de plataformas como LinkedIn, Instagram y Facebook. Además, tuve la oportunidad de aprender a utilizar Odoo como empleado para gestionar documentos relacionados con los recursos humanos. Esta experiencia me permitió mejorar mis habilidades en comunicación empresarial y comprender la gestión de documentos dentro de un entorno corporativo.",
    /* ------------------------------- Site Studio ------------------------------ */
    "studio-site-project-desc" => "STUDIO LAB'UT es un estudio profesional dedicado a la creación sonora, a la formación y al acompañamiento de artistas, situado en Estrasburgo. En el marco de mi pasantía, me encargaron diseñar un sitio escaparate con la herramienta Carrd, para presentar eficazmente las actividades del estudio, sus formaciones y sus equipamientos (<a href=\"https://labut.xyz/\" target=\"_blank\">labut.xyz</a>). Este proyecto me ha permitido estructurar la información de manera clara y visual, teniendo en cuenta las necesidades de un público diverso (estudiantes, intermitentes, artistas). También me aseguré de valorar la identidad del estudio trabajando en una línea gráfica coherente y una navegación fluida. Esta experiencia me ha permitido reforzar mis habilidades en diseño web, comunicación visual y accesibilidad de la información.",
    /* ------------------------------- Com Studio ------------------------------- */
    "com-studio-project-desc" => "En el marco de mi pasantía en STUDIO LAB'UT, un espacio dedicado a la creación sonora y a la formación artística, he desarrollado una estrategia de comunicación digital en Instagram, Facebook y LinkedIn. He implementado una línea editorial coherente con los valores del estudio (creatividad, accesibilidad, excelencia) y diseñado visuales adaptados a cada plataforma. Paralelamente, he desarrollado una carta gráfica para reforzar la identidad visual del estudio y asegurar un mejor reconocimiento entre nuestro público objetivo (estudiantes, intermitentes, artistas emergentes).",
    /* ------------------------------- Space game ------------------------------- */
    "game-project-desc" => "My New Solar System es un simple juego espacial en 2D creado con Java en el entorno IntelliJ. El objetivo es controlar una estrella que recoge planetas para formar su propio sistema solar. El juego tiene un sistema por turnos: cada acción del jugador provoca movimientos de todas las entidades, en este caso, las estrellas hostiles y la materia oscura. Los niveles se construyen a partir de cuadrículas de caracteres, lo que permite un diseño flexible del mapa. Los recursos visuales fueron diseñados utilizando Canva. El proyecto demuestra principios de programación orientada a objetos, mecánicas por turnos y técnicas de generación de niveles.",
    /* --------------------------------- Memoire -------------------------------- */
    "memoire-title" => "Memoria - Licenciatura Profesional",
    "memoire-desc" => "Durante mi año de Licencia Profesional en Estrategia de Comunicación e Información Digital, desarrollé un mémoire en Ciencias de la Información y de la Comunicación. Esta página presenta un resumen de dicho trabajo, sin constituir una publicación científica oficial.
    La investigación se centra en el crecimiento del marketing de influencia y en el papel de la autodivulgación de los influencers como estrategia de contenido. <br>
    <br>La pregunta principal que guió el estudio fue: ¿En qué medida la autodivulgación de los influencers en las redes sociales constituye una estrategia de contenidos que permite reforzar las relaciones parasociales con su audiencia?<br>
    <br>
    La metodología empleada combinó una revisión teórica en comunicación, psicología social y marketing con un estudio cualitativo mediante análisis de contenido de cuatro influencers estadounidenses en Instagram y YouTube. 
    Los resultados demuestran que la autodivulgación, cuando es percibida como sincera, favorece la percepción de autenticidad y la construcción de una imagen identificable, lo que fortalece la confianza y la lealtad de la audiencia. Esta dinámica emocional permite a los influencers diferenciarse en un entorno saturado y legitima sus recomendaciones comerciales, además de ajustarse a las lógicas algorítmicas que privilegian los contenidos con fuerte carga emocional. 
    Sin embargo, es importante señalar que las relaciones parasociales son fenómenos comunes y no necesariamente negativos, y que la autodivulgación, aunque poderosa, no constituye por sí sola una garantía de éxito. 
    Entre las perspectivas de investigación futura se destaca la necesidad de profundizar en el punto de vista de la audiencia y en su nivel de alfabetización algorítmica, con el fin de comprender mejor cómo se configuran las experiencias digitales.",
    "notioncolab-title"=> "Herramienta de trabajo colaborativo + guía",
    "notioncolab-desc"=> "He configurado un espacio de trabajo en Notion para STUDIO LAB'UT, un estudio de creación sonora y formación, para facilitar la gestión de proyectos y la colaboración en equipo. El espacio de trabajo incluye secciones para el seguimiento de proyectos, asignación de tareas y compartición de recursos, lo que permite a los miembros del equipo mantenerse organizados e informados. Además, he creado una guía de usuario para ayudar al equipo a utilizar eficazmente las funciones de Notion, asegurando una adopción fluida y maximizando la productividad. Esta implementación ha mejorado la comunicación y el flujo de trabajo dentro del estudio, permitiendo una ejecución de proyectos más eficiente.",
    /* --------------------------------- Memoire M-------------------------------- */
"memoire-master-title" => "Mémoire - Master en Sciences Cognitives",
"memoire-master-desc" => "Durante mi Máster en Ciencias Cognitivas, estoy llevando a cabo un proyecto de investigación de dos años bajo la supervisión de <a href='https://pro.univ-lille.fr/arthur-prevel'>Arthur Prével</a>. El proyecto se centra en el sesgo de automatización (automation bias) en los sistemas de apoyo a la toma de decisiones (Decision Support Systems, DSS), un tipo de sistema autónomo. El proyecto de investigación se desarrolla a lo largo de los dos años de mi Máster.<br><br>El primer año estuvo dedicado al desarrollo teórico y metodológico del proyecto, incluyendo la revisión de la literatura, la formulación de las hipótesis y el diseño del protocolo experimental. Durante este periodo, también desarrollé y programé el experimento en línea como parte de mis 210 horas de prácticas, lo que me permitió realizar un estudio piloto inicial y evaluar el procedimiento experimental. (Consulta esta página para obtener más información sobre las prácticas.) <br><br>Actualmente, el proyecto está entrando en su segundo año. La siguiente etapa consiste en implementar la versión final del experimento en línea con una muestra más amplia de participantes. Esta fase permitirá recopilar un conjunto de datos considerablemente mayor, lo que hará posible llevar a cabo los análisis principales y obtener conclusiones más sólidas sobre el sesgo de automatización, la transparencia del sistema y la dependencia de los sistemas de apoyo a la toma de decisiones. <br><br>Tanto mi proyecto de investigación de Máster como mis prácticas fueron financiados en el marco del proyecto <a href='https://initiative-excellence.univ-lille.fr/nos-projets-structurants/mener-une-recherche-dexcellence/cross-disciplinary-projects/cdp-deperu'>DePERU (Decision-making Processes under Extreme Radical Uncertainties)</a>, un proyecto de investigación multidisciplinar de la Universidad de Lille. Mi director de tesis de Máster, Arthur Prével, participa en este proyecto dentro del Eje 3: Choice.",
"memoire-master-research-question" => "¿Cómo interactúan las variaciones en la transparencia del sistema y las contingencias de recompensa para influir en la dependencia condicionada de un sistema de apoyo a la toma de decisiones?",
"memoire-master-abstract" => "Los sistemas autónomos de apoyo a la toma de decisiones pueden mejorar el rendimiento, pero también pueden aumentar el sesgo de automatización cuando los usuarios confían en ellos de manera acrítica. Por ello, este estudio busca determinar cómo interactúan la transparencia del sistema y las contingencias de recompensa para influir en la dependencia condicionada de un sistema de apoyo a la toma de decisiones. El objetivo principal era determinar si la incorporación de información sobre la transparencia del sistema y la manipulación de las consecuencias asociadas a las respuestas correctas e incorrectas podían modificar el rendimiento, los comportamientos de dependencia y la calibración de la confianza. El estudio se llevó a cabo inicialmente con una muestra piloto de 13 participantes, mediante un diseño experimental mixto. Los participantes realizaron una tarea de detección de objetos en imágenes de rayos X bajo tres condiciones de asistencia mediante IA: sin IA, IA opaca e IA transparente. Se asignaron entre participantes dos tipos de contingencias de recompensa: una condición de ganancia únicamente y una condición de ganancia y pérdida. La precisión y los tiempos de reacción se analizaron mediante ANOVA mixtos. Asimismo, se compararon las tasas de acuerdo con las recomendaciones de la IA entre las distintas condiciones, particularmente durante las fases normal, de error y posterior al error. Los resultados no mostraron efectos significativos de la contingencia de recompensa sobre la precisión, los tiempos de reacción o la carga de trabajo, ni diferencias significativas en la precisión global entre las distintas condiciones de asistencia mediante IA. Sin embargo, la condición de IA transparente presentó los tiempos de reacción más rápidos. En conclusión, los resultados de este estudio piloto sugieren que la transparencia puede favorecer un mejor ajuste de la confianza hacia el sistema, mientras que la manipulación de las recompensas tuvo un efecto limitado y no medible en este estudio piloto.",
];
?>